# Base configs
baseurl: "https://yakubovich.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Ilya Yakubovich Photography"
subtitle: "What I Saw"
author: "Ilya Yakubovich"
header:
 title: "Photography"
 subtitle: "by Ilya Yakubovich"
footer:
 name: "Hi"
 bio: ""
 github: ""
web_design: ""
social_urls:
  instagram: "https://www.instagram.com/ilya.yak"
  flickr: "https://www.flickr.com/yakubovich"
  500px: "https://www.500px.com/yakubovich"
